services:
  app:
    build:
      args:
        user: shortener
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: shortener
    container_name: shortener-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - shortener

  db:
    image: mysql:8.0
    container_name: shortener-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: DB_NAME
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASS
      MYSQL_PASSWORD: DB_PASS
      MYSQL_USER: DB_USER
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - shortener

  nginx:
    image: nginx:alpine
    container_name: shortener-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shortener

networks:
  shortener:
    driver: bridge
      
